### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by rjsonbiz** [orangehill/iseed#106]
Hi.
In order to support L55, the IseedCommand must have a handle() method instead of a fire() method()
https://github.com/laravel/framework/blob/master/CHANGELOG-5.5.md
https://github.com/laravel/framework/pull/19827
https://github.com/laravel/framework/pull/20024

Cheers

**Comment by tihomiro** [comment]
Implemented in https://github.com/orangehill/iseed/releases/tag/v2.5.1
