### ISSUE TITLE
IseedCommand::handle() does not exist

### ISSUE THREAD

**Issue by tomerBZ** [orangehill/iseed#110]
Laravel 5.5
\Orangehill\Iseed\IseedServiceProvider::class is on the providers array (config/app.php)
"orangehill/iseed": "dev-master" on composer.json

Command: php artisan iseed table_name
Error:
[ReflectionException]                                          
Method Orangehill\Iseed\IseedCommand::handle() does not exist

**Comment by archfrog** [comment]
This is a known problem.  You can temporarily fix it by adding this code to IseedCommand.php in the vendor/orangehill/... directory:

        public function handle()
        {
                return $this->fire();
        } 

That's what I did.  I suppose the people making iseed are busy as people have made pull requests with no merge as of yet.  I guess it is a matter of days or weeks until we see a compatible version of iseed.

**Comment by tomerBZ** [comment]
Worked like magic :sparkles:
Thanks A lot

**Comment by tihomiro** [comment]
Hey guys, sorry for not being able to test & PR yet, we're pretty busy launching a major project so hold on for a few days more ;)

**Comment by tihomiro** [comment]
Implemented in https://github.com/orangehill/iseed/releases/tag/v2.5.1
