### ISSUE TITLE
Foreign key constraint fails 

### ISSUE THREAD

**Issue by Luc45** [orangehill/iseed#117]
I generated the seeds in my local environment, but when I try to run `php artisan db:seed` on development environment, it returns the following message:

>  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`admin_patrimar`.`bairros`, CONSTRAINT
>    `fk_bairro_cidade1` FOREIGN KEY (`cidade_id`) REFERENCES `pracas` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
> 

![image](https://user-images.githubusercontent.com/9341686/34836578-75a4501c-f6df-11e7-8516-9b891a5092e0.png)

**Comment by Luc45** [comment]
I managed to solve it after tweaking several times the order of seeds on DatabaseSeeder.php

**Comment by DaveWishesHe** [comment]
Appreciate that you've resolved your issue, but for future reference - rather than tweaking the DatabaseSeeder file over and over to find the correct order, you can update like this:

```
public function run()
{
    Schema::disableForeignKeyConstraints();

    // $this->call(...) methods here.

    Schema::enableForeignKeyConstraints();
}
```

Should work cross-platform.

**Comment by olivsinz** [comment]
Here's what works for me

```
public function run(): void
{
    if (DB::connection() instanceof SQLiteConnection) {
        DB::statement('PRAGMA FOREIGN_KEYS=0');
    } elseif (DB::connection() instanceof PostgresConnection) {
        DB::statement("SET session_replication_role = 'replica';");
    } else {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
    }

   // $this->call([....]) methods here.
   
    if (DB::connection() instanceof SQLiteConnection) {
          DB::statement('PRAGMA FOREIGN_KEYS=1');
      } elseif (DB::connection() instanceof PostgresConnection) {
          DB::statement("SET session_replication_role = 'origin';");
      } else {
          DB::statement('SET FOREIGN_KEY_CHECKS=1');
      }
}
```
