### ISSUE TITLE
why my git-gui could not track this repository iseed?

### ISSUE THREAD

**Issue by jianhuawang** [orangehill/iseed#120]
## why my git-gui could not track this repository iseed?
I change my composer.json as "orangehill/iseed": "dev-master", and update.
all files of iseed have been downloaded and placed in  my_project/vendor/orangehill.
and then, I will push all files to my git server, 
but My git-gui could not track this respository iseed .
even though I run:
 git add -f ./vendor/*
 git-gui didn't track iseed any files either.

Is there any one meet this situation? 
Who know why? I need help, thanks in advance

![git-gui](https://user-images.githubusercontent.com/16495687/38230809-531fd180-3742-11e8-8be1-0d732a540faf.PNG)

**Comment by DaveWishesHe** [comment]
Can you share the contents of any .gitignore files that might be impacting this project?

Personally I don't commit the vendor directory to source control at all (https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md) but I did just initialise a new git repo and `composer require orangehill/iseed`, the files did track as expected.

**Comment by terrywamg** [comment]
@DaveWishesHe  I am sorry for I didn't explain my issue clearly. I mean I can not commit iseed to my git server because git-gui does not track this repository.
