### ISSUE TITLE
iseed not writing connection info to seed files?

### ISSUE THREAD

**Issue by archfrog** [orangehill/iseed#123]
I have a setup where I use two databases, `mysql` and `mysql2`.  When I reverse seed from table 2 (`mysql2`), using the `--database=mysql2` command-line option, a mostly correct seed file is generated, but it does **not** seed back into the proper table.

The problem seems to be that `iseed` does not output "connection" information.  It outputs:

    \DB::table('events')->delete();
    \DB::table('events')->insert(array(...));

Where it should have output this:

    \DB::connection('mysql2')->table('events')->delete();
    \DB::connection('mysql2')->table('events')->insert(array(...));

I think this is a bug in `iseed`, but I am not absolutely sure :-)

I am using PHP v7.2, Laravel v5.6, and Percona v5.7 (MySQL compatible like MariaDB).

**Comment by tihomiro** [comment]
Just tested using https://github.com/orangehill/iseed#database command option and everything works as expected. If you find that this is still an issue, please share some test DB data and we'll double-check.

**Comment by tihomiro** [comment]
OK, so to make things clearer, I'm specifying my database connections in `config/database.php` and the connections key looks like this:
```    'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

        'mysql2' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE_2', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
```
and in my .env file I have:

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=iseed-test
DB_DATABASE_2=iseed-test2
DB_USERNAME=root
DB_PASSWORD=
```
Is this how you have your system set up (as this is the recommended approach)?

**Comment by archfrog** [comment]
I don't have the `DB_DATABASE_2` key in my `.env` file as it is "hard-coded" in the `database.php` file.  I don't think that should make any difference?  But I can try it out and see if that helps.

**Comment by tihomiro** [comment]
It shouldn't make much of a difference. To make sure that you don't have any configuration quirks on your end, could you try the following:

1. Start a new Laravel project with iSeed included
2. Create 2 databases
3. Inside of each database create the same structured table called e.g. 'test'
4. Create different entries in each of the tables
5. Setup two db connections
6. Try to export data using the --database iseed option

This works for me. If it works for you on a vanilla Laravel project, you might want to check for details in your project that are possibly not related to iseed.

**Comment by archfrog** [comment]
I think we're talking past each other :-)  

The problem is that I cannot reseed the second database.  The inverse seed works fine, but once I try `artisan db:seed`, the operation fails because of the missing connection info.

If I search the `iseed` source code, then I cannot find any code to output the missing `DB::connection('mysql2')->` code.  In `populateStub`, there's no code to output the connection info.  It just outputs `\DB::table('%s')->insert(%s)`.

**Comment by tihomiro** [comment]
OK, I finally gotcha! :)

You need to use the `--database` option while seeding, like this: `php artisan db:seed --database=mysql2`
