### ISSUE TITLE
[PROPOSAL] Generate seeds for all tables with one command

### ISSUE THREAD

**Issue by ArtemMolotov** [orangehill/iseed#129]
#24

Example of implementation:
```bash
php artisan iseed:all
```

Or 

```bash
php artisan iseed
```

```php
    /**
     * @var \Doctrine\DBAL\Connection $conn
     */
    $sm = $conn->getSchemaManager();
    $fullSchema = $sm->createSchema();
    $tables = $fullSchema->getTables(); // exclude 'migrations'

    foreach ($tables as $table) {
        // code for one table
    }
```

**Comment by ArtemMolotov** [comment]
Currently we can use:
```php
class ISeedAllCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'iseed:all';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Make seeders for all tables by iseed';

    /**
     * @var Connection
     */
    protected $connection;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
        $this->connection = DB::getDoctrineConnection();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $tableNames = $this->getShortestTableNames();
        $tableNames = array_diff($tableNames, ['migrations']);

        Artisan::call('iseed', [
            'tables' => implode(',', $tableNames),
            '--force' => true,
        ]);

        return true;
    }

    protected function getShortestTableNames(): array
    {
        $sm = $this->connection->getSchemaManager();
        $databaseName = $this->connection->getDatabase();

        $fullSchema = $sm->createSchema();
        $tableNames = $fullSchema->getTableNames();

        $shortTableNames = str_replace("$databaseName.", '', $tableNames);

        return $shortTableNames;
    }
}
```

**Comment by famarojr** [comment]
Error:

In excel.php line 182:
Class 'PHPExcel_Shared_Font' not found

**Comment by ArtemMolotov** [comment]
Hi! Are your comment related to the current topic?

**Comment by famarojr** [comment]
Yes. I did this e get this error.

**Comment by ArtemMolotov** [comment]
Can you show your `excel.php` or try https://github.com/Maatwebsite/Laravel-Excel/issues/1654?

**Comment by famarojr** [comment]
**composer.json**
`"require": { 
...
"maatwebsite/excel": "^3.0",
....
}`

**config/excel.php**

`<?php

return array(

    'cache'      => [

        /*
        |--------------------------------------------------------------------------
        | Enable/Disable cell caching
        |--------------------------------------------------------------------------
        */
        'enable'   => true,

        /*
        |--------------------------------------------------------------------------
        | Caching driver
        |--------------------------------------------------------------------------
        |
        | Set the caching driver
        |
        | Available methods:
        | memory|gzip|serialized|igbinary|discISAM|apc|memcache|temp|wincache|sqlite|sqlite3
        |
        */
        'driver'   => 'memory',

        /*
        |--------------------------------------------------------------------------
        | Cache settings
        |--------------------------------------------------------------------------
        */
        'settings' => [

            'memoryCacheSize' => '32MB',
            'cacheTime'       => 600

        ],

        /*
        |--------------------------------------------------------------------------
        | Memcache settings
        |--------------------------------------------------------------------------
        */
        'memcache' => [

            'host' => 'localhost',
            'port' => 11211,

        ],

        /*
        |--------------------------------------------------------------------------
        | Cache dir (for discISAM)
        |--------------------------------------------------------------------------
        */

        'dir'      => storage_path('cache')
    ],

    'properties' => [
        'creator'        => 'Maatwebsite',
        'lastModifiedBy' => 'Maatwebsite',
        'title'          => 'Spreadsheet',
        'description'    => 'Default spreadsheet export',
        'subject'        => 'Spreadsheet export',
        'keywords'       => 'maatwebsite, excel, export',
        'category'       => 'Excel',
        'manager'        => 'Maatwebsite',
        'company'        => 'Maatwebsite',
    ],

    /*
    |--------------------------------------------------------------------------
    | Sheets settings
    |--------------------------------------------------------------------------
    */
    'sheets'     => [

        /*
        |--------------------------------------------------------------------------
        | Default page setup
        |--------------------------------------------------------------------------
        */
        'pageSetup' => [
            'orientation'           => 'portrait',
            'paperSize'             => '9',
            'scale'                 => '100',
            'fitToPage'             => false,
            'fitToHeight'           => true,
            'fitToWidth'            => true,
            'columnsToRepeatAtLeft' => ['', ''],
            'rowsToRepeatAtTop'     => [0, 0],
            'horizontalCentered'    => false,
            'verticalCentered'      => false,
            'printArea'             => null,
            'firstPageNumber'       => null,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Creator
    |--------------------------------------------------------------------------
    |
    | The default creator of a new Excel file
    |
    */

    'creator'    => 'Maatwebsite',

    'csv'        => [
        /*
       |--------------------------------------------------------------------------
       | Delimiter
       |--------------------------------------------------------------------------
       |
       | The default delimiter which will be used to read out a CSV file
       |
       */

        'delimiter'   => ',',

        /*
        |--------------------------------------------------------------------------
        | Enclosure
        |--------------------------------------------------------------------------
        */

        'enclosure'   => '"',

        /*
        |--------------------------------------------------------------------------
        | Line endings
        |--------------------------------------------------------------------------
        */

        'line_ending' => "\r\n",

        /*
        |--------------------------------------------------------------------------
        | setUseBom
        |--------------------------------------------------------------------------
        */

        'use_bom' => false
    ],

    'export'     => [

        /*
        |--------------------------------------------------------------------------
        | Autosize columns
        |--------------------------------------------------------------------------
        |
        | Disable/enable column autosize or set the autosizing for
        | an array of columns ( array('A', 'B') )
        |
        */
        'autosize'                    => true,

        /*
        |--------------------------------------------------------------------------
        | Autosize method
        |--------------------------------------------------------------------------
        |
        | --> PHPExcel_Shared_Font::AUTOSIZE_METHOD_APPROX
        | The default is based on an estimate, which does its calculation based
        | on the number of characters in the cell value (applying any calculation
        | and format mask, and allowing for wordwrap and rotation) and with an
        | "arbitrary" adjustment based on the font (Arial, Calibri or Verdana,
        | defaulting to Calibri if any other font is used) and a proportional
        | adjustment for the font size.
        |
        | --> PHPExcel_Shared_Font::AUTOSIZE_METHOD_EXACT
        | The second method is more accurate, based on actual style formatting as
        | well (bold, italic, etc), and is calculated by generating a gd2 imagettf
        | bounding box and using its dimensions to determine the size; but this
        | method is significantly slower, and its accuracy is still dependent on
        | having the appropriate fonts installed.
        |
        */
        'autosize-method'             => PHPExcel_Shared_Font::AUTOSIZE_METHOD_APPROX,

        /*
        |--------------------------------------------------------------------------
        | Auto generate table heading
        |--------------------------------------------------------------------------
        |
        | If set to true, the array indices (or model attribute names)
        | will automatically be used as first row (table heading)
        |
        */
        'generate_heading_by_indices' => true,

        /*
        |--------------------------------------------------------------------------
        | Auto set alignment on merged cells
        |--------------------------------------------------------------------------
        */
        'merged_cell_alignment'       => 'left',

        /*
        |--------------------------------------------------------------------------
        | Pre-calculate formulas during export
        |--------------------------------------------------------------------------
        */
        'calculate'                   => false,

        /*
        |--------------------------------------------------------------------------
        | Include Charts during export
        |--------------------------------------------------------------------------
        */
        'includeCharts'               => false,

        /*
        |--------------------------------------------------------------------------
        | Default sheet settings
        |--------------------------------------------------------------------------
        */
        'sheets'                      => [

            /*
            |--------------------------------------------------------------------------
            | Default page margin
            |--------------------------------------------------------------------------
            |
            | 1) When set to false, default margins will be used
            | 2) It's possible to enter a single margin which will
            |    be used for all margins.
            | 3) Alternatively you can pass an array with 4 margins
            |    Default order: array(top, right, bottom, left)
            |
            */
            'page_margin'          => false,

            /*
            |--------------------------------------------------------------------------
            | Value in source array that stands for blank cell
            |--------------------------------------------------------------------------
            */
            'nullValue'            => null,

            /*
            |--------------------------------------------------------------------------
            | Insert array starting from this cell address as the top left coordinate
            |--------------------------------------------------------------------------
            */
            'startCell'            => 'A1',

            /*
            |--------------------------------------------------------------------------
            | Apply strict comparison when testing for null values in the array
            |--------------------------------------------------------------------------
            */
            'strictNullComparison' => false
        ],

        /*
        |--------------------------------------------------------------------------
        | Store settings
        |--------------------------------------------------------------------------
        */

        'store'                       => [

            /*
            |--------------------------------------------------------------------------
            | Path
            |--------------------------------------------------------------------------
            |
            | The path we want to save excel file to
            |
            */
            'path'       => storage_path('exports'),

            /*
            |--------------------------------------------------------------------------
            | Return info
            |--------------------------------------------------------------------------
            |
            | Whether we want to return information about the stored file or not
            |
            */
            'returnInfo' => false

        ],

        /*
        |--------------------------------------------------------------------------
        | PDF Settings
        |--------------------------------------------------------------------------
        */
        'pdf'                         => [

            /*
            |--------------------------------------------------------------------------
            | PDF Drivers
            |--------------------------------------------------------------------------
            | Supported: DomPDF, tcPDF, mPDF
            */
            'driver'  => 'DomPDF',

            /*
            |--------------------------------------------------------------------------
            | PDF Driver settings
            |--------------------------------------------------------------------------
            */
            'drivers' => [

                /*
                |--------------------------------------------------------------------------
                | DomPDF settings
                |--------------------------------------------------------------------------
                */
                'DomPDF' => [
                    'path' => base_path('vendor/dompdf/dompdf/')
                ],

                /*
                |--------------------------------------------------------------------------
                | tcPDF settings
                |--------------------------------------------------------------------------
                */
                'tcPDF'  => [
                    'path' => base_path('vendor/tecnick.com/tcpdf/')
                ],

                /*
                |--------------------------------------------------------------------------
                | mPDF settings
                |--------------------------------------------------------------------------
                */
                'mPDF'   => [
                    'path' => base_path('vendor/mpdf/mpdf/')
                ],
            ]
        ]
    ],

    'filters'    => [
        /*
        |--------------------------------------------------------------------------
        | Register read filters
        |--------------------------------------------------------------------------
        */

        'registered' => [
            'chunk' => 'Maatwebsite\Excel\Filters\ChunkReadFilter'
        ],

        /*
        |--------------------------------------------------------------------------
        | Enable certain filters for every file read
        |--------------------------------------------------------------------------
        */

        'enabled'    => []
    ],

    'import'     => [

        /*
        |--------------------------------------------------------------------------
        | Has heading
        |--------------------------------------------------------------------------
        |
        | The sheet has a heading (first) row which we can use as attribute names
        |
        | Options: true|false|slugged|slugged_with_count|ascii|numeric|hashed|hashed_with_lower|trans|original
        |
        */

        'heading'                 => 'slugged',

        /*
        |--------------------------------------------------------------------------
        | First Row with data or heading of data
        |--------------------------------------------------------------------------
        |
        | If the heading row is not the first row, or the data doesn't start
        | on the first row, here you can change the start row.
        |
        */

        'startRow'                => 1,

        /*
        |--------------------------------------------------------------------------
        | Cell name word separator
        |--------------------------------------------------------------------------
        |
        | The default separator which is used for the cell names
        | Note: only applies to 'heading' settings 'true' && 'slugged'
        |
        */

        'separator'               => '_',

        /*
        |--------------------------------------------------------------------------
        | Slug whitelisting
        |--------------------------------------------------------------------------
        |
        | Here you can whitelist certain characters in the slug.
        | E.g. user.last_name will not remove . and _
        | Note: only applies to 'heading' settings 'true' && 'slugged'
        |
        */

        'slug_whitelist'       => '._',

        /*
        |--------------------------------------------------------------------------
        | Include Charts during import
        |--------------------------------------------------------------------------
        */

        'includeCharts'           => false,

        /*
        |--------------------------------------------------------------------------
        | Sheet heading conversion
        |--------------------------------------------------------------------------
        |
        | Convert headings to ASCII
        | Note: only applies to 'heading' settings 'true' && 'slugged'
        |
        */

        'to_ascii'                => true,

        /*
        |--------------------------------------------------------------------------
        | Import encoding
        |--------------------------------------------------------------------------
        */

        'encoding'                => [

            'input'  => 'UTF-8',
            'output' => 'UTF-8'

        ],

        /*
        |--------------------------------------------------------------------------
        | Calculate
        |--------------------------------------------------------------------------
        |
        | By default cells with formulas will be calculated.
        |
        */

        'calculate'               => true,

        /*
        |--------------------------------------------------------------------------
        | Ignore empty cells
        |--------------------------------------------------------------------------
        |
        | By default empty cells are not ignored
        |
        */

        'ignoreEmpty'             => false,

        /*
        |--------------------------------------------------------------------------
        | Force sheet collection
        |--------------------------------------------------------------------------
        |
        | For a sheet collection even when there is only 1 sheets.
        | When set to false and only 1 sheet found, the parsed file will return
        | a row collection instead of a sheet collection.
        | When set to true, it will return a sheet collection instead.
        |
        */
        'force_sheets_collection' => false,

        /*
        |--------------------------------------------------------------------------
        | Date format
        |--------------------------------------------------------------------------
        |
        | The format dates will be parsed to
        |
        */

        'dates'                   => [

            /*
            |--------------------------------------------------------------------------
            | Enable/disable date formatting
            |--------------------------------------------------------------------------
            */
            'enabled' => true,

            /*
            |--------------------------------------------------------------------------
            | Default date format
            |--------------------------------------------------------------------------
            |
            | If set to false, a carbon object will return
            |
            */
            'format'  => false,

            /*
            |--------------------------------------------------------------------------
            | Date columns
            |--------------------------------------------------------------------------
            */
            'columns' => []
        ],

        /*
        |--------------------------------------------------------------------------
        | Import sheets by config
        |--------------------------------------------------------------------------
        */
        'sheets'                  => [

            /*
            |--------------------------------------------------------------------------
            | Example sheet
            |--------------------------------------------------------------------------
            |
            | Example sheet "test" will grab the firstname at cell A2
            |
            */

            'test' => [

                'firstname' => 'A2'

            ]

        ]
    ],

    'views'      => [

        /*
        |--------------------------------------------------------------------------
        | Styles
        |--------------------------------------------------------------------------
        |
        | The default styles which will be used when parsing a view
        |
        */

        'styles' => [

            /*
            |--------------------------------------------------------------------------
            | Table headings
            |--------------------------------------------------------------------------
            */
            'th'     => [
                'font' => [
                    'bold' => true,
                    'size' => 12,
                ]
            ],

            /*
            |--------------------------------------------------------------------------
            | Strong tags
            |--------------------------------------------------------------------------
            */
            'strong' => [
                'font' => [
                    'bold' => true,
                    'size' => 12,
                ]
            ],

            /*
            |--------------------------------------------------------------------------
            | Bold tags
            |--------------------------------------------------------------------------
            */
            'b'      => [
                'font' => [
                    'bold' => true,
                    'size' => 12,
                ]
            ],

            /*
            |--------------------------------------------------------------------------
            | Italic tags
            |--------------------------------------------------------------------------
            */
            'i'      => [
                'font' => [
                    'italic' => true,
                    'size'   => 12,
                ]
            ],

            /*
            |--------------------------------------------------------------------------
            | Heading 1
            |--------------------------------------------------------------------------
            */
            'h1'     => [
                'font' => [
                    'bold' => true,
                    'size' => 24,
                ]
            ],

            /*
            |--------------------------------------------------------------------------
            | Heading 2
            |--------------------------------------------------------------------------
            */
            'h2'     => [
                'font' => [
                    'bold' => true,
                    'size' => 18,
                ]
            ],

            /*
            |--------------------------------------------------------------------------
            | Heading 3
            |--------------------------------------------------------------------------
            */
            'h3'     => [
                'font' => [
                    'bold' => true,
                    'size' => 13.5,
                ]
            ],

            /*
             |--------------------------------------------------------------------------
             | Heading 4
             |--------------------------------------------------------------------------
             */
            'h4'     => [
                'font' => [
                    'bold' => true,
                    'size' => 12,
                ]
            ],

            /*
             |--------------------------------------------------------------------------
             | Heading 5
             |--------------------------------------------------------------------------
             */
            'h5'     => [
                'font' => [
                    'bold' => true,
                    'size' => 10,
                ]
            ],

            /*
             |--------------------------------------------------------------------------
             | Heading 6
             |--------------------------------------------------------------------------
             */
            'h6'     => [
                'font' => [
                    'bold' => true,
                    'size' => 7.5,
                ]
            ],

            /*
             |--------------------------------------------------------------------------
             | Hyperlinks
             |--------------------------------------------------------------------------
             */
            'a'      => [
                'font' => [
                    'underline' => true,
                    'color'     => ['argb' => 'FF0000FF'],
                ]
            ],

            /*
             |--------------------------------------------------------------------------
             | Horizontal rules
             |--------------------------------------------------------------------------
             */
            'hr'     => [
                'borders' => [
                    'bottom' => [
                        'style' => 'thin',
                        'color' => ['FF000000']
                    ],
                ]
            ]
        ]

    ]

);
`

**Comment by ArtemMolotov** [comment]
> **composer.json**
> `"require": { ... "maatwebsite/excel": "^3.0", .... }`
> 
> **config/excel.php**
> 
> `<?php
> 
> return array(
> 
> ```
> 'cache'      => [
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Enable/Disable cell caching
>     |--------------------------------------------------------------------------
>     */
>     'enable'   => true,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Caching driver
>     |--------------------------------------------------------------------------
>     |
>     | Set the caching driver
>     |
>     | Available methods:
>     | memory|gzip|serialized|igbinary|discISAM|apc|memcache|temp|wincache|sqlite|sqlite3
>     |
>     */
>     'driver'   => 'memory',
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Cache settings
>     |--------------------------------------------------------------------------
>     */
>     'settings' => [
> 
>         'memoryCacheSize' => '32MB',
>         'cacheTime'       => 600
> 
>     ],
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Memcache settings
>     |--------------------------------------------------------------------------
>     */
>     'memcache' => [
> 
>         'host' => 'localhost',
>         'port' => 11211,
> 
>     ],
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Cache dir (for discISAM)
>     |--------------------------------------------------------------------------
>     */
> 
>     'dir'      => storage_path('cache')
> ],
> 
> 'properties' => [
>     'creator'        => 'Maatwebsite',
>     'lastModifiedBy' => 'Maatwebsite',
>     'title'          => 'Spreadsheet',
>     'description'    => 'Default spreadsheet export',
>     'subject'        => 'Spreadsheet export',
>     'keywords'       => 'maatwebsite, excel, export',
>     'category'       => 'Excel',
>     'manager'        => 'Maatwebsite',
>     'company'        => 'Maatwebsite',
> ],
> 
> /*
> |--------------------------------------------------------------------------
> | Sheets settings
> |--------------------------------------------------------------------------
> */
> 'sheets'     => [
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Default page setup
>     |--------------------------------------------------------------------------
>     */
>     'pageSetup' => [
>         'orientation'           => 'portrait',
>         'paperSize'             => '9',
>         'scale'                 => '100',
>         'fitToPage'             => false,
>         'fitToHeight'           => true,
>         'fitToWidth'            => true,
>         'columnsToRepeatAtLeft' => ['', ''],
>         'rowsToRepeatAtTop'     => [0, 0],
>         'horizontalCentered'    => false,
>         'verticalCentered'      => false,
>         'printArea'             => null,
>         'firstPageNumber'       => null,
>     ],
> ],
> 
> /*
> |--------------------------------------------------------------------------
> | Creator
> |--------------------------------------------------------------------------
> |
> | The default creator of a new Excel file
> |
> */
> 
> 'creator'    => 'Maatwebsite',
> 
> 'csv'        => [
>     /*
>    |--------------------------------------------------------------------------
>    | Delimiter
>    |--------------------------------------------------------------------------
>    |
>    | The default delimiter which will be used to read out a CSV file
>    |
>    */
> 
>     'delimiter'   => ',',
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Enclosure
>     |--------------------------------------------------------------------------
>     */
> 
>     'enclosure'   => '"',
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Line endings
>     |--------------------------------------------------------------------------
>     */
> 
>     'line_ending' => "\r\n",
> 
>     /*
>     |--------------------------------------------------------------------------
>     | setUseBom
>     |--------------------------------------------------------------------------
>     */
> 
>     'use_bom' => false
> ],
> 
> 'export'     => [
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Autosize columns
>     |--------------------------------------------------------------------------
>     |
>     | Disable/enable column autosize or set the autosizing for
>     | an array of columns ( array('A', 'B') )
>     |
>     */
>     'autosize'                    => true,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Autosize method
>     |--------------------------------------------------------------------------
>     |
>     | --> PHPExcel_Shared_Font::AUTOSIZE_METHOD_APPROX
>     | The default is based on an estimate, which does its calculation based
>     | on the number of characters in the cell value (applying any calculation
>     | and format mask, and allowing for wordwrap and rotation) and with an
>     | "arbitrary" adjustment based on the font (Arial, Calibri or Verdana,
>     | defaulting to Calibri if any other font is used) and a proportional
>     | adjustment for the font size.
>     |
>     | --> PHPExcel_Shared_Font::AUTOSIZE_METHOD_EXACT
>     | The second method is more accurate, based on actual style formatting as
>     | well (bold, italic, etc), and is calculated by generating a gd2 imagettf
>     | bounding box and using its dimensions to determine the size; but this
>     | method is significantly slower, and its accuracy is still dependent on
>     | having the appropriate fonts installed.
>     |
>     */
>     'autosize-method'             => PHPExcel_Shared_Font::AUTOSIZE_METHOD_APPROX,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Auto generate table heading
>     |--------------------------------------------------------------------------
>     |
>     | If set to true, the array indices (or model attribute names)
>     | will automatically be used as first row (table heading)
>     |
>     */
>     'generate_heading_by_indices' => true,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Auto set alignment on merged cells
>     |--------------------------------------------------------------------------
>     */
>     'merged_cell_alignment'       => 'left',
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Pre-calculate formulas during export
>     |--------------------------------------------------------------------------
>     */
>     'calculate'                   => false,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Include Charts during export
>     |--------------------------------------------------------------------------
>     */
>     'includeCharts'               => false,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Default sheet settings
>     |--------------------------------------------------------------------------
>     */
>     'sheets'                      => [
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Default page margin
>         |--------------------------------------------------------------------------
>         |
>         | 1) When set to false, default margins will be used
>         | 2) It's possible to enter a single margin which will
>         |    be used for all margins.
>         | 3) Alternatively you can pass an array with 4 margins
>         |    Default order: array(top, right, bottom, left)
>         |
>         */
>         'page_margin'          => false,
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Value in source array that stands for blank cell
>         |--------------------------------------------------------------------------
>         */
>         'nullValue'            => null,
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Insert array starting from this cell address as the top left coordinate
>         |--------------------------------------------------------------------------
>         */
>         'startCell'            => 'A1',
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Apply strict comparison when testing for null values in the array
>         |--------------------------------------------------------------------------
>         */
>         'strictNullComparison' => false
>     ],
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Store settings
>     |--------------------------------------------------------------------------
>     */
> 
>     'store'                       => [
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Path
>         |--------------------------------------------------------------------------
>         |
>         | The path we want to save excel file to
>         |
>         */
>         'path'       => storage_path('exports'),
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Return info
>         |--------------------------------------------------------------------------
>         |
>         | Whether we want to return information about the stored file or not
>         |
>         */
>         'returnInfo' => false
> 
>     ],
> 
>     /*
>     |--------------------------------------------------------------------------
>     | PDF Settings
>     |--------------------------------------------------------------------------
>     */
>     'pdf'                         => [
> 
>         /*
>         |--------------------------------------------------------------------------
>         | PDF Drivers
>         |--------------------------------------------------------------------------
>         | Supported: DomPDF, tcPDF, mPDF
>         */
>         'driver'  => 'DomPDF',
> 
>         /*
>         |--------------------------------------------------------------------------
>         | PDF Driver settings
>         |--------------------------------------------------------------------------
>         */
>         'drivers' => [
> 
>             /*
>             |--------------------------------------------------------------------------
>             | DomPDF settings
>             |--------------------------------------------------------------------------
>             */
>             'DomPDF' => [
>                 'path' => base_path('vendor/dompdf/dompdf/')
>             ],
> 
>             /*
>             |--------------------------------------------------------------------------
>             | tcPDF settings
>             |--------------------------------------------------------------------------
>             */
>             'tcPDF'  => [
>                 'path' => base_path('vendor/tecnick.com/tcpdf/')
>             ],
> 
>             /*
>             |--------------------------------------------------------------------------
>             | mPDF settings
>             |--------------------------------------------------------------------------
>             */
>             'mPDF'   => [
>                 'path' => base_path('vendor/mpdf/mpdf/')
>             ],
>         ]
>     ]
> ],
> 
> 'filters'    => [
>     /*
>     |--------------------------------------------------------------------------
>     | Register read filters
>     |--------------------------------------------------------------------------
>     */
> 
>     'registered' => [
>         'chunk' => 'Maatwebsite\Excel\Filters\ChunkReadFilter'
>     ],
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Enable certain filters for every file read
>     |--------------------------------------------------------------------------
>     */
> 
>     'enabled'    => []
> ],
> 
> 'import'     => [
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Has heading
>     |--------------------------------------------------------------------------
>     |
>     | The sheet has a heading (first) row which we can use as attribute names
>     |
>     | Options: true|false|slugged|slugged_with_count|ascii|numeric|hashed|hashed_with_lower|trans|original
>     |
>     */
> 
>     'heading'                 => 'slugged',
> 
>     /*
>     |--------------------------------------------------------------------------
>     | First Row with data or heading of data
>     |--------------------------------------------------------------------------
>     |
>     | If the heading row is not the first row, or the data doesn't start
>     | on the first row, here you can change the start row.
>     |
>     */
> 
>     'startRow'                => 1,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Cell name word separator
>     |--------------------------------------------------------------------------
>     |
>     | The default separator which is used for the cell names
>     | Note: only applies to 'heading' settings 'true' && 'slugged'
>     |
>     */
> 
>     'separator'               => '_',
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Slug whitelisting
>     |--------------------------------------------------------------------------
>     |
>     | Here you can whitelist certain characters in the slug.
>     | E.g. user.last_name will not remove . and _
>     | Note: only applies to 'heading' settings 'true' && 'slugged'
>     |
>     */
> 
>     'slug_whitelist'       => '._',
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Include Charts during import
>     |--------------------------------------------------------------------------
>     */
> 
>     'includeCharts'           => false,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Sheet heading conversion
>     |--------------------------------------------------------------------------
>     |
>     | Convert headings to ASCII
>     | Note: only applies to 'heading' settings 'true' && 'slugged'
>     |
>     */
> 
>     'to_ascii'                => true,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Import encoding
>     |--------------------------------------------------------------------------
>     */
> 
>     'encoding'                => [
> 
>         'input'  => 'UTF-8',
>         'output' => 'UTF-8'
> 
>     ],
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Calculate
>     |--------------------------------------------------------------------------
>     |
>     | By default cells with formulas will be calculated.
>     |
>     */
> 
>     'calculate'               => true,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Ignore empty cells
>     |--------------------------------------------------------------------------
>     |
>     | By default empty cells are not ignored
>     |
>     */
> 
>     'ignoreEmpty'             => false,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Force sheet collection
>     |--------------------------------------------------------------------------
>     |
>     | For a sheet collection even when there is only 1 sheets.
>     | When set to false and only 1 sheet found, the parsed file will return
>     | a row collection instead of a sheet collection.
>     | When set to true, it will return a sheet collection instead.
>     |
>     */
>     'force_sheets_collection' => false,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Date format
>     |--------------------------------------------------------------------------
>     |
>     | The format dates will be parsed to
>     |
>     */
> 
>     'dates'                   => [
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Enable/disable date formatting
>         |--------------------------------------------------------------------------
>         */
>         'enabled' => true,
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Default date format
>         |--------------------------------------------------------------------------
>         |
>         | If set to false, a carbon object will return
>         |
>         */
>         'format'  => false,
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Date columns
>         |--------------------------------------------------------------------------
>         */
>         'columns' => []
>     ],
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Import sheets by config
>     |--------------------------------------------------------------------------
>     */
>     'sheets'                  => [
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Example sheet
>         |--------------------------------------------------------------------------
>         |
>         | Example sheet "test" will grab the firstname at cell A2
>         |
>         */
> 
>         'test' => [
> 
>             'firstname' => 'A2'
> 
>         ]
> 
>     ]
> ],
> 
> 'views'      => [
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Styles
>     |--------------------------------------------------------------------------
>     |
>     | The default styles which will be used when parsing a view
>     |
>     */
> 
>     'styles' => [
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Table headings
>         |--------------------------------------------------------------------------
>         */
>         'th'     => [
>             'font' => [
>                 'bold' => true,
>                 'size' => 12,
>             ]
>         ],
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Strong tags
>         |--------------------------------------------------------------------------
>         */
>         'strong' => [
>             'font' => [
>                 'bold' => true,
>                 'size' => 12,
>             ]
>         ],
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Bold tags
>         |--------------------------------------------------------------------------
>         */
>         'b'      => [
>             'font' => [
>                 'bold' => true,
>                 'size' => 12,
>             ]
>         ],
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Italic tags
>         |--------------------------------------------------------------------------
>         */
>         'i'      => [
>             'font' => [
>                 'italic' => true,
>                 'size'   => 12,
>             ]
>         ],
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Heading 1
>         |--------------------------------------------------------------------------
>         */
>         'h1'     => [
>             'font' => [
>                 'bold' => true,
>                 'size' => 24,
>             ]
>         ],
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Heading 2
>         |--------------------------------------------------------------------------
>         */
>         'h2'     => [
>             'font' => [
>                 'bold' => true,
>                 'size' => 18,
>             ]
>         ],
> 
>         /*
>         |--------------------------------------------------------------------------
>         | Heading 3
>         |--------------------------------------------------------------------------
>         */
>         'h3'     => [
>             'font' => [
>                 'bold' => true,
>                 'size' => 13.5,
>             ]
>         ],
> 
>         /*
>          |--------------------------------------------------------------------------
>          | Heading 4
>          |--------------------------------------------------------------------------
>          */
>         'h4'     => [
>             'font' => [
>                 'bold' => true,
>                 'size' => 12,
>             ]
>         ],
> 
>         /*
>          |--------------------------------------------------------------------------
>          | Heading 5
>          |--------------------------------------------------------------------------
>          */
>         'h5'     => [
>             'font' => [
>                 'bold' => true,
>                 'size' => 10,
>             ]
>         ],
> 
>         /*
>          |--------------------------------------------------------------------------
>          | Heading 6
>          |--------------------------------------------------------------------------
>          */
>         'h6'     => [
>             'font' => [
>                 'bold' => true,
>                 'size' => 7.5,
>             ]
>         ],
> 
>         /*
>          |--------------------------------------------------------------------------
>          | Hyperlinks
>          |--------------------------------------------------------------------------
>          */
>         'a'      => [
>             'font' => [
>                 'underline' => true,
>                 'color'     => ['argb' => 'FF0000FF'],
>             ]
>         ],
> 
>         /*
>          |--------------------------------------------------------------------------
>          | Horizontal rules
>          |--------------------------------------------------------------------------
>          */
>         'hr'     => [
>             'borders' => [
>                 'bottom' => [
>                     'style' => 'thin',
>                     'color' => ['FF000000']
>                 ],
>             ]
>         ]
>     ]
> 
> ]
> ```
> );
> `

**Comment by ArtemMolotov** [comment]
@famarojr, your error is not related to this feature. Please, see [solution in the comment](https://github.com/Maatwebsite/Laravel-Excel/issues/1654#issuecomment-387304199).

**Comment by ArtemMolotov** [comment]
@famarojr, your comment about this feature:

 > Now, I have this return:
There are no commands defined in the "iseed" namespace.

Did you create a file (e.g. `ISeedAllCommand.php` ) in the `app/Console/Commands` directory with [the code that is placed above](https://github.com/orangehill/iseed/issues/129#issuecomment-421010939)?

**Comment by ArtemMolotov** [comment]
Can you delete comments about `LaravelExcel`?

**Comment by tihomiro** [comment]
Closing. More info: https://github.com/orangehill/iseed/issues/58#issuecomment-268492946
