### ISSUE TITLE
Laravel 5.6 only has table->delete() in the seeder

### ISSUE THREAD

**Issue by greylegface** [orangehill/iseed#131]
When I create a new seeder using `php artisan iseed {table}` it creates the seeder file, but the only command in there is 

`\DB::table('users')->delete();`

I am using "dev-master" branch and Laravel 5.6

just to add to this, I have a database with about 30 tables, all with columns defined. I have tried seeding an individual table and it just gives me the above, with no errors present.

**Comment by badrshs** [comment]
I have same issue  , did you solve it ?
