### ISSUE TITLE
Add support for Laravel 6.0

### ISSUE THREAD

**Issue by alvinbakker** [orangehill/iseed#144]
Please add support for Laravel 6.0
Thanx

**Comment by jamesliang1226** [comment]
Iseed is a good tool for laravel, I am moving the old project from laravel 5 to laravel 6, I hope iseed can support laravel 6, thanks for ur job, good job !

**Comment by gregoryxg** [comment]
This is great, and I don't see why Laravel doesn't include this in the PHP Artisan CLI. Please add support for 6.0! Thanks!

**Comment by nuernbergerA** [comment]
@tihomiro pls merge, we need this :)
