### ISSUE TITLE
Command: php artisan db:seed not working

### ISSUE THREAD

**Issue by aseerishraque** [orangehill/iseed#175]
Please Fix the namespaces in the generated seeder files located in laravel app. Location: database/seeds/UsersTableSeeder.php

**Comment by LeonLoong** [comment]
Laravel 8 
C:\xampp\htdocs\pms/database/seeders/
Laravel 7 and previous versions 
C:\xampp\htdocs\pms/database/seeds/

**Comment by LeonLoong** [comment]
someone is already pull request for this 
https://github.com/orangehill/iseed/pull/167/commits/3c6626f5989c504009e0865ffaf1e07d54f62ade

**Comment by tihomiro** [comment]
Yeah, this is done in https://github.com/orangehill/iseed/releases/tag/v3.0
