### ISSUE TITLE
[Feature Request] Max # of rows

### ISSUE THREAD

**Issue by bkuhl** [orangehill/iseed#18]
I'm not sure how this would play out with foreign keys, maybe it'd just need to ignore them?  I have several tables I'd like to generate seeds for that exceed 1,000 rows and I only need about 50 for development purposes.  It'd be awesome to be able to specify a max # of rows to be seeded from a given table.

**Comment by NightfallSD** [comment]
Feature implemented, using option --max from command line. More info in README.md 

Closing this issue.
