### ISSUE TITLE
iseed cannot put table seeders in DatabaseSeeder.php according to foreign key relationships 

### ISSUE THREAD

**Issue by parmonov98** [orangehill/iseed#184]
it throws errors if some table linked via foreign key and the table seeders are stacked in a wrong order.

**Comment by adgower** [comment]
> it throws errors if some table linked via foreign key and the table seeders are stacked in a wrong order.

If not critical you can always modify the seeder to add
top:
`Schema::disableForeignKeyConstraints();`
bottom:
`Schema::enableForeignKeyConstraints();`
