### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by akoevroman** [orangehill/iseed#204]
![image](https://user-images.githubusercontent.com/14367411/153243675-4ab534a1-736c-4581-839f-31e50425fbfe.png)

Will Laravel 9 support be added to this package?

**Comment by raulamoretti** [comment]
I m with the same problem.


Problem 1
    - Root composer.json requires orangehill/iseed dev-master -> satisfiable by orangehill/iseed[dev-master].
    - orangehill/iseed dev-master requires illuminate/support ~5.5.0|~5.6.0|~5.7.0|~5.8.0|^6.0|^7.0|^8.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9).

**Comment by adgower** [comment]
same problem
