### ISSUE TITLE
Overwrites existing file without warning.

### ISSUE THREAD

**Issue by markfee** [orangehill/iseed#21]
This is a really useful tool, its not a huge problem for me as I have my seed files in a repository, but an existing seed file was overwritten without warning when run from artisan. A prompt or an overwrite flag would be even better.

**Comment by NightfallSD** [comment]
Artisan confirm method implemented every time user tries to overwrite existing seed file. Also option --force included that will by default overwrite existing seeds.

Thank you for your suggestion.

**Comment by markfee** [comment]
Thanks for fixing and for letting me know.

Cheers.
