### ISSUE TITLE
Doesn't work with model events

### ISSUE THREAD

**Issue by ziming** [orangehill/iseed#26]
Expected behaviour:
When every record is gets created, I expect my model created event to fire off to do some other things.

Actual Behaviour:
My model event created method is only called once, instead of once for each record created. This only happened to seeder files generated by iSeed. Possibly due to iSeed auto generated seeder files using bulk inserts (If I don't remember wrongly)

**Comment by tihomiro** [comment]
Yes, that is correct. Database table rows are inserted in bulk, so you don't get an event fired for each row entered. This is not possible with iSeed, and it will not be implemented as a feature, sorry.
