### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by davidsoderberg** [orangehill/iseed#32]
Hi, could you please make this package avaible to use with laravel 5.

**Comment by davidsoderberg** [comment]
Hi, have made a fork of your repo and it works with Laravel 5, do I have your permission to submit it to https://packagist.org/? 

Check it out here: https://github.com/davidsoderberg/iseed

**Comment by tihomiro** [comment]
Hi,

I'd prefer if we can test your branch and merge it with ours. 

I hope that we'll be able to test by the end of next week. 

Thanks,
Tihomir

**Comment by davidsoderberg** [comment]
I have made a fork from a fork of this so how can we merge it?

**Comment by tihomiro** [comment]
I just went through commits that you've made ever since forking. We've made some significant changes after you've forked iSeed, so I think that the fastest way to merge would be if we use your commits as a  reference to manually upgrade iSeed to L5.

Thanks!

**Comment by davidsoderberg** [comment]
Ok, then we do like that, I will use my fork to you have an Iseed that works with L5.

**Comment by codesmith55** [comment]
I'm interested and excited to use this project in L5, is any help required to make the updates?

**Comment by grumpysi** [comment]
Can't wait for the L5 version.  Awesome package, thanks.

**Comment by rhyudek1** [comment]
I tried to install the davidsoderberg's package but it gave me errors, I'll wait the merge..

**Comment by davidsoderberg** [comment]
What type of error did you get @rhyudek1 ?

**Comment by rhyudek1** [comment]
this appear when I run composer update
```
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package davidsoderberg/iseed could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by davidsoderberg** [comment]
Please check the readme file for my repo :smile:

**Comment by soft7solutions** [comment]
@davidsoderberg I have the same error as @rhyudek1 
I did everything as instructed in the readme file. (Included repositories).

**Comment by soft7solutions** [comment]
@davidsoderberg @rhyudek1 I finally got it solved. The version given in the require must match versions in the git repo. I had to do a "composer show" to see the available versions which i then found out that there was no "master" version and it was suppose to be "dev-master". So change "davidsoderberg/iseed": "master" --to-- "davidsoderberg/iseed": "dev-master". 

You should have it updated in the readme file.

**Comment by davidsoderberg** [comment]
Thanks will fix that later :)

**Comment by davidsoderberg** [comment]
@soft7solutions @rhyudek1 now it is updated :smile:

**Comment by NightfallSD** [comment]
Project updated so that it works on Laravel 5. If someone still wishes to use it on Laravel 4 they should use tag 1.1 of this repo instead of dev-master. Detailed info soon in readme file.

**Comment by tihomiro** [comment]
Guys, I'm closing this issue as we're done with adding support for L5. If anyone notices any problem please open a new issue. Thanks all!
