### ISSUE TITLE
Error:: While composer update

### ISSUE THREAD

**Issue by rebin** [orangehill/iseed#33]
We receive this error while doing composer update

  Error Output: PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::configPath() in /home/muthu/project/xport/server/vendor/orangehill/iseed/src  
  /Orangehill/Iseed/IseedServiceProvider.php on line 67

**Comment by NightfallSD** [comment]
Hi rebin. Thx for your input. 

Could you please paste your composer file? This problem could occur if you are trying to update dev-master branch into Laravel 4 project. If that is the case you should use 1.1 version of iSeed.

**Comment by tihomiro** [comment]
Closing as there's been no response for more then 40 days.
