### ISSUE TITLE
composer dump-autoload required

### ISSUE THREAD

**Issue by vedmant** [orangehill/iseed#39]
Hi, there is a problem, it requires to launch composer dump-autoload when new seed class is created. Maybe it's good to add dump-autoload command execution when launching php artisan iseed?

Also it adds $this->call() to DatabaseSeeder after Model::reguard(); call, it should be before. And in new Laravel 5.1 version they replaced tabs indents with spaces http://screencast.com/t/pAAUENCFzg6F

**Comment by tihomiro** [comment]
Implemented composer dump-autoload feature with https://github.com/orangehill/iseed/pull/81
