### ISSUE TITLE
does not work on Laravel 5.1

### ISSUE THREAD

**Issue by unitedworx** [orangehill/iseed#41]
Just installed this on 5.1 but it does not work. Whatever I try I keep getting the below error! Althought `php artisan vendor:publish` does not seem to publish the package config file i have created it manually with no luck. Also when running the command i added the max option and still no luck. 

`php artisan iseed users -max=100`

```
[ErrorException]                                             
  array_chunk(): Size parameter expected to be greater than 0
```

**Comment by laimisf** [comment]
I have no problems with Laravel 5.1.
Great package ;)

**Comment by michellaurent** [comment]
Same as @laimisf, works fine for me with Laravel 5.1

**Comment by tihomiro** [comment]
It's been a while. Checked this - works as expected. 

For what it's worth there's a typo in a command issued `php artisan iseed users -max=100` should be `php artisan iseed users --max=100`
