### ISSUE TITLE
[ReflectionException] Class TableNameTableSeeder does not exist

### ISSUE THREAD

**Issue by philxtian** [orangehill/iseed#43]
I was able to create seed classes using iseed command. But when I try to re-seed the data by running  php artisan db:seed command, this error shows up:

[ReflectionException] Class TableNameTableSeeder does not exist

I'm using Laravel 5.1.

Thanks.

**Comment by Endlessline** [comment]
This isn't really an issue with the code, you need to run composer dump to reload the classmap then it works

**Comment by philxtian** [comment]
I already managed to fix this using the same method you mentioned. Thanks.
