### ISSUE TITLE
what happend with L5 branch???

### ISSUE THREAD

**Issue by gbelot2003** [orangehill/iseed#44]
Thanks for your hard work,
It seems you deleted the dev-master branch, my cuestion is, will you enabled dev-master branch again? ? will be some changes??

thanks again!!

**Comment by tihomiro** [comment]
Hi,
We feel that iSeed is pretty much right where we want it. Not so many feature requests were rolling in, so I guess everyone feels that it's pretty OK, too. If you have any feature requests please let us know and we'll consider it for future development.

Other than that we're just making sure that we're compatible with actual Laravel version.

**Comment by gbelot2003** [comment]
Thanks tihomoro,
First, thaks for answer, ISeed is a pretty nice job, no cuestion about.
Im asking becose I got a composer error when trying to reach Iseed, if I use dev-master, there is no repo, if I use master, composer no recognice :/ that why Im asking, sorry for the misunderstandig
