### ISSUE TITLE
Problem with space

### ISSUE THREAD

**Issue by gregory-vc** [orangehill/iseed#49]
https://github.com/orangehill/iseed/blob/master/src/Orangehill/Iseed/Iseed.php#L273

I store yml file in database, after export all structure be fail.
Why ltrim?

**Comment by tihomiro** [comment]
Hey @gregory-vc can you please share example data with me? A mysqldump of a table with some yml data would be perfect for me to test.

**Comment by tihomiro** [comment]
@gregory-vc I'm going to close this issue as there's no response, but feel free to reopen this at ny time once you have some data to share with me.

**Comment by gregory-vc** [comment]
Hi, ok, it happen so many times ago, so i forget all :)
