### ISSUE TITLE
database connection in IseedCommand.php

### ISSUE THREAD

**Issue by csambrus** [orangehill/iseed#51]
Please change the hasTable check in generateFileName 
https://github.com/orangehill/iseed/blob/master/src/Orangehill/Iseed/IseedCommand.php#L158
to 
if (!\Schema::connection($database)->hasTable($table)) {

and add
$database = $this->option('database') ?: config('database.default');
to
https://github.com/orangehill/iseed/blob/master/src/Orangehill/Iseed/IseedCommand.php#L51

and change
https://github.com/orangehill/iseed/blob/master/src/Orangehill/Iseed/IseedCommand.php#L70
to:
list($fileName, $className) = $this->generateFileName($database, $table);

Thanks.

**Comment by PaulVisscher** [comment]
I can confirm these changes are needed for multi database projects.

**Comment by tihomiro** [comment]
Fixed.
