### ISSUE TITLE
[Question] Iseed Backup

### ISSUE THREAD

**Issue by nicolaeturcan** [orangehill/iseed#53]
Hello everyone. 

My question is, can iseed be used as a backup of the information from a table? For example, I want to do regular backup of a table data in seed format every day or maybe every week automatically and without overriding the old seeders. Is there a way to do that?

**Comment by tihomiro** [comment]
Perhaps it's better to use a true backup solution such as this: https://github.com/spatie/laravel-backup

**Comment by nicolaeturcan** [comment]
Thanks you @tihomiro, looks like what I need.
