### ISSUE TITLE
Question: seeding only results of a select query

### ISSUE THREAD

**Issue by tpharaoh** [orangehill/iseed#57]
This is not an issue, rather a question.

I use another laravel provider which seeds 2 rows in 2 tables. I need all rows in 3 tables for the application to work. Do you have a way where I could generate a seed from results of a eloquent query? Model::where('id','>','2')

**Comment by tihomiro** [comment]
No, this is not possible with iSeed. iSeed was conceived as a database table(s) synchronization tool.
