### ISSUE TITLE
Work with Lumen

### ISSUE THREAD

**Issue by shaneparsons** [orangehill/iseed#59]
It looks like Lumen doesn't pull in some packages that iseed rely on – e.g. `\Illuminate\Foundation`

**Comment by jazlopez** [comment]
Lumen is a lightweight framework out of box though tweaking is possible.

**Comment by tihomiro** [comment]
Yeah, out of the box iSeed doesn't work with Lumen, though expanding Lumen to be able to run iSeed is definitely possible.
