### ISSUE TITLE
Laravel 5.3 changes

### ISSUE THREAD

**Issue by rsdev000** [orangehill/iseed#63]
Hi everyone!

Laravel 5.3 is around the corner and this package needs some changes to work with it.

See the getData() method:

```php
    /**
     * Get the Data
     * @param  string $table
     * @return Array
     */
    public function getData($table, $max)
    {
        if (!$max) {
            return \DB::connection($this->databaseName)->table($table)->get();
        }

        return \DB::connection($this->databaseName)->table($table)->limit($max)->get();
    }
```

Prior to L5.3 this method returns an array but in L5.3+ it returns a Collection that needs to be casted as an array.

Dirty quick fix to allow this package to work with both L5.3 and prior versions.

```php
    /**
     * Repacks data read from the database
     * @param  array|object $data
     * @return array
     */
    public function repackSeedData($data)
    {
        // Check if $data is an array
        if (!is_array($data)) {
            $data = $data->toArray();
        }

        $dataArray = array();
        if (is_array($data)) {
            foreach ($data as $row) {
                $rowArray = array();

                foreach ($row as $columnName => $columnValue) {
                    $rowArray[$columnName] = $columnValue;
                }
                $dataArray[] = $rowArray;
            }
        }
        return $dataArray;
    }
```

Cheers

**Comment by jorgeneira** [comment]
Thank you, I really hope the maintainer of this package allows it to run on L 5.3. I'm not too optimistic though, I've been months waiting for a PR that I did to be merged, Its an small change (adds ::class notation for seeder classnames in DatabaseSeeder.php) but I haven't received any feedback from the author =(

**Comment by rsdev000** [comment]
@jorgeneira  You're welcome. Sometimes there's not enough time to keep side projects running and I understand that can be frustrating for someone that spends it's time contributing, doesn't get any feedback from the e but let's keep hope :)

Cheers

**Comment by tihomiro** [comment]
Hey guys, and thanks so much for your participation. My colleague @NightfallSD who usually maintains this package has been totally blocked by a project for a client and literary didn't have enough breathing room to merge pending PRs. We thought it'd be best if we wait for him to do the merging, as he knows the project inside out, but the client is relentless. We'll definitely make time to at least tackle the L5.3 issue, and try hard to handle all other PRs while doing so.

**Comment by xvlady** [comment]
i registred xvlady/iseed on packagist.org with this fast chenge
"require": {
    "xvlady/iseed": "dev-master"
}
or
"require": {
    "xvlady/iseed": "2.3.0"
}

**Comment by tihomiro** [comment]
Thanks for patience guys. Added the L5.3 compatibility.
