### ISSUE TITLE
Fail in laravel 5.3

### ISSUE THREAD

**Issue by agrodriguez** [orangehill/iseed#66]
Hi, I use " php artisan iseed my_table " but only get 
`<?php

use Illuminate\Database\Seeder;

class my_tableTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('my_table')->delete();
    }
}
`
please help
thanks

**Comment by lukasoppermann** [comment]
Same here.

**Comment by 2601-Srl** [comment]
Same here.

**Comment by lukasoppermann** [comment]
Ahh, stupid mistake, just follow the readme:

**1) For Laravel 5 instalation edit your project's composer.json file to require orangehill/iseed.**

```
"require": {
    "orangehill/iseed": "dev-master"
}
```

**Comment by 2601-Srl** [comment]
Just a quick suggestion. 

Probably it depends on the way 5.3 returns query builder calls to [collection rather than array](https://laracasts.com/series/whats-new-in-laravel-5-3/episodes/2).

A dirty and not completely tested fix could be done to **iseed.php** on **line 63**

from
`$data = $this->getData($table, $max);`

to
`$data = $this->getData($table, $max)->toArray();`

**Comment by tihomiro** [comment]
There was an actual problem which is now fixed. I also tagged a v2.2 as L5.3 compatible.

**Comment by agrodriguez** [comment]
I've followed the readme, that's why i'm  asking, son
my composer.json is as follows
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "laravelcollective/html": "5.3.*",
        "doctrine/dbal": "^2.5",
        "orangehill/iseed": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*",
        "krlove/eloquent-model-generator": "^1.2"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

**Comment by tihomiro** [comment]
@agrodriguez are you still having an issue?

**Comment by agrodriguez** [comment]
Nop, no issue, I tought that the generator created the seeder class using the DDL to create  the corresponding faker data to fill up the table. Something like 
       `'address' => $faker->address,
        'address2' => $faker->secondaryAddress,
        'district' => $faker->state,
        'city_id' => $faker->numberBetween(1, 600),
        'postal_code' => $faker->postcode,
        'phone' => $faker->phoneNumber,
        'location' => $faker->latitude().','.$faker->longitude(),`
Even if it was just  $faker->realText(<lengthOfTheField>) or $faker->randomNumber(x)
But it just instead takes the data already in the table and extracts it to a seeder class file, much like a dumpfile.
it works fine with data on the table, just not what i was looking for tho.
Thanks

**Comment by tihomiro** [comment]
Yeah, this is not the package that does that, definitely. We're working on such functionality, but it will be available only as a part of our CMS system http://photoncms.com/. The CMS will allow you to build table structures and CRUD modules, and in the process let you set faker-like settings for each table field that will automatically generate seed data for any of created tables. 

It should speed up the development process by at least an hour or two.
