### ISSUE TITLE
Is there a way to generate seeds ignoring columns?

### ISSUE THREAD

**Issue by arturhayne** [orangehill/iseed#72]
When I generate seeds with autoincrement columns the database lost the reference of those fields when I have to run/restore the seed, causing a duplicated key error in the moment that I add a new register of this table. This is commonly happens with id primary keys that I have to delete it from generated seed. Because of that I need to know if there is any way to generate the seed ignoring the autoincrement id columns.

My database is Postgres.

Congrats for the project!

**Comment by tihomiro** [comment]
Implemented in https://github.com/orangehill/iseed/pull/80
