### ISSUE TITLE
command iseed is not defined  error in laravel 5.3

### ISSUE THREAD

**Issue by shihabudheenf** [orangehill/iseed#74]
After installing the package, When I am trying `php artisan iseed my_table` in command line, I am getting error that command iseed is not defined.

**Comment by GlassSteel** [comment]
Did you remember to add Orangehill\Iseed\IseedServiceProvider::class to the config/app.php providers array?

**Comment by bertalanimre** [comment]
What if I've done the same, but still no luck. I can see the composer update have done the installing (without putting Orangehill\Iseed\IseedServiceProvider::class into the app.php file. But after this, still not working.

[Symfony\Component\Debug\Exception\FatalErrorException]         
  Class 'Orangehill\Iseed\IseedServiceProvider::class' not found

**Comment by tihomiro** [comment]
We're actually using a ::class notation as of https://github.com/orangehill/iseed/commit/aeb1453671db795fcb8a53e1a7bcf6b4e4c0dfa9 so correct way to update the app.php file is to add 
```
Orangehill\Iseed\IseedServiceProvider::class
```
tp providers array.

**Comment by buglinjo** [comment]
I have the same issue. I have added to providers array: `Orangehill\Iseed\IseedServiceProvider::class,`
but it says: `Command "iseed" is not defined.`.

**Comment by tihomiro** [comment]
@buglinjo just tested this with blank new laravel installation, following the provided iseed instructions and everything worked. Please verify that you are following instructions to the letter.

**Comment by MysticD2** [comment]
Make sure you clean the config and cache before running `php artisan iseed ...` with `php artisan config:cache`

**Comment by tspesh** [comment]
Concur with @MysticD2 .  Clearing the cache and it worked like a charm. Saving me a huge headache too to boot!
