### ISSUE TITLE
Generated seed whithout update DatabaseSeeder file

### ISSUE THREAD

**Issue by pcampello** [orangehill/iseed#77]
Hi guys,

search but not found generated seed whithout update DatabaseSeeder file.
I would like to update the seed file from a table but do not change the databaseSeeder file, is this possible?
Sorry my English. :smiley:

**Comment by tihomiro** [comment]
No, this is not possible. 

In case you need to create a seed file for the same table over and over, that's possible. Just issue the same command. You'll also be prompted if you want to overwrite an existing seed file or not.

**Comment by relaypilot** [comment]
This is a feature I'd require too, is it still not possible now?

The reason is that I am using a cron task that calls the Artisan command to backup my tables as seeder files, but I would like to avoid updating the `DatabaseSeeder.php` file.
