### ISSUE TITLE
Class 'Illuminate\Support\Composer' not found

### ISSUE THREAD

**Issue by csoseman** [orangehill/iseed#83]
After updating to the latest of iseed (`dev-master`) I receive the following error when using `composer require` or `composer update`

![2017-01-02_0-46-39](https://cloud.githubusercontent.com/assets/8847249/21585405/fdd058a0-d084-11e6-85c8-142cbbcb0011.png)

I am using L5.1. I believe that L5.1 uses Illuminate\Foundation\Composer instead of Illuminate\Foundation\Composer. I was able to put a bandaid on this by specifying a previous commit in composer.json and running `composer update --no-scripts` to get me by for now. If you need anything else let me know.

Thanks for all the work you do on this package. It's greatly appreciated!

**Comment by tihomiro** [comment]
Tested this by issuing `composer create-project laravel/laravel iseeddebug 5.1` and afterward installing iseed as per provided instructions. `composer update` worked without throwing an exception. @csoseman can you please reproduce the error in a blank new Laravel installation and let me know the steps so that I can replicate in my environment? Thanks!

**Comment by richardbenson** [comment]
Had the same bug, forcing to 2.2 in composer.json solved it.  The error was being thrown in iseed, but was triggered by running barryvdh/laravel-ide-helper commands as part of composer post-update.

5.1 does use Illuminate\Foundation\Composer whereas for 5.2+ they switched to Illuminate\Support\Composer

Will try and help with a repro later, but I would imagine running any iseed command after the composer update will trigger it.

**Comment by tihomiro** [comment]
Resolved by including "illuminate/support": "~5.3.8" as a requirement in composer.json https://github.com/orangehill/iseed/blob/master/composer.json#L14

This means that L 5.1 projects will need to require a previous iseed version "orangehill/iseed": "2.2" .
