### ISSUE TITLE
Unable to install on Laravel 5.2

### ISSUE THREAD

**Issue by agasigp** [orangehill/iseed#84]
I'm using Laravel 5.2 and want to install this package but I cannot install it. Here is my error after I run composer update : 
![screenshot from 2017-01-16 14-00-12](https://cloud.githubusercontent.com/assets/2476867/21973564/2a9072e2-dbf4-11e6-949a-fc77f34182aa.png)
![screenshot from 2017-01-16 14-01-06](https://cloud.githubusercontent.com/assets/2476867/21973578/3f98d30a-dbf4-11e6-9639-fbfe4aa8506c.png)

Is it possible to install it on Laravel 5.2?

**Comment by tihomiro** [comment]
You need to use "orangehill/iseed": "2.2" instead of "orangehill/iseed": "dev-master" in your composer.json, as Laravel 5.3.8 is the minimum requirement for the latest iseed version.
