### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by dwijpr** [orangehill/iseed#86]
- orangehill/iseed dev-master requires illuminate/support ~5.3.8 -> satisfiable by laravel/framework[v5.3.28], illuminate/support[v5.3.16, v5.3.23].
    - orangehill/iseed dev-master requires illuminate/support ~5.3.8 -> satisfiable by laravel/framework[v5.3.28], illuminate/support[v5.3.16, v5.3.23].
    - don't install laravel/framework v5.4.0|don't install illuminate/support v5.3.16
    - don't install laravel/framework v5.4.0|don't install illuminate/support v5.3.23
    - Can only install one of: laravel/framework[v5.4.0, v5.3.28].
    - Installation request for laravel/framework 5.4.* -> satisfiable by laravel/framework[v5.4.0].
    - Installation request for orangehill/iseed dev-master -> satisfiable by orangehill/iseed[dev-master].

**Comment by vesper8** [comment]
Hrm, oddly I was able to install it regardless, however there is a problem.

In the Iseed service provider you make use of app->share but this method was removed from 5.4:

https://laravel.com/docs/5.4/upgrade

```
share Method Removed

The share method has been removed from the container. This was a legacy method that has not been documented in several years. If you are using this method, you should begin using the  singleton method instead:

$container->singleton('foo', function () {
    return 'foo';
});
```

**Comment by tihomiro** [comment]
Yes, there's already a PR here https://github.com/orangehill/iseed/pull/85 just waiting for a minor update and I'll merge.

**Comment by tihomiro** [comment]
L5.4 support added. Thanks guys.
