### ISSUE TITLE
Laravel 5.4 Support?

### ISSUE THREAD

**Issue by mrkatz** [orangehill/iseed#89]
I get this error when I run php artisan comand after regisering this package.
Call to undefined method Illuminate\Foundation\Application::share()
 I'm guessing the share() function has been renamed??

**Comment by mrkatz** [comment]
Just noticed you have it updated...but not yet published. Thanks For The Update.

**Comment by tihomiro** [comment]
Thanks for reminding me, just tagged a version :)
