### ISSUE TITLE
I've updated to 5.4 and now getting segmantation problem

### ISSUE THREAD

**Issue by jaysg** [orangehill/iseed#90]
Hi, we were using this iseed perfectly with 5.3 now its not working with 5.4

when I run this 
`
php artisan iseed product_types
`
I get this as an error
`
Segmentation fault: 11
`

**Comment by tihomiro** [comment]
can you please share the product_types table dump with me so that I can try to reproduce?

**Comment by jaysg** [comment]
when I run `php artisan iseed product_types` on the terminal i get this  error

                              
  ```
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "iseed" is not defined.          
``` 

I've already ran composer update this my coposer.json
```{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "intervention/image": "^2.3",
        "laravel/dusk": "^1.0",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "nesbot/carbon": "^1.22",
        "orangehill/iseed": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*",
        "heroku/heroku-buildpack-php": "*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
}
```

**Comment by jaysg** [comment]
sorry I forgot i had commented it out of the providers. But still having the same error 
`Segmentation fault: 11`

**Comment by jaysg** [comment]
```
/*
-- Query: SELECT * FROM 39dglaravel.product_types
LIMIT 0, 1000

-- Date: 2017-02-15 17:01
*/
INSERT INTO `product_types` (`id`,`created_at`,`updated_at`,`title`) VALUES (1,'2017-02-15 19:44:10','2017-02-15 19:44:10','Frame');
INSERT INTO `product_types` (`id`,`created_at`,`updated_at`,`title`) VALUES (2,'2017-02-15 19:44:10','2017-02-15 19:44:10','Contact');
INSERT INTO `product_types` (`id`,`created_at`,`updated_at`,`title`) VALUES (3,'2017-02-15 19:44:10','2017-02-15 19:44:10','Lens');
```

**Comment by tihomiro** [comment]
@jaysg like I said: can you please share the product_types table dump with me so that I can try to reproduce?

**Comment by younesdiouri** [comment]
Hello, (23 days later ;) ) I got the same problem. When I add it to the provider list (laravel 5.4), after a composer update, it doesn't recognize the Iseed class .
indeed, on the shell, I got a " Class 'Orangehill\Iseed\IseedServiceProvider' not found" problem. 
I will try to put it into the require-dev composer.json section, to see if there is any difference . 
Thanks !

**Comment by Leomhl** [comment]
I have the same problem!

**Comment by younesdiouri** [comment]
tell us more ^^

**Comment by nermand** [comment]
Problem is, I think, with this: 
` [Symfony\Component\Debug\Exception\FatalThrowableError]
Call to undefined method Illuminate\Foundation\Application::share()`

Apparently, as of Laravel 5.4 `share `has been removed and `singleton `should be used instead.
[Commit](https://github.com/laravel/framework/commit/1a1969b6e6f793c3b2a479362641487ee9cbf736)

**Comment by juslintek** [comment]
I have the same problem iseed is not listed in artisan commands.

**Comment by tihomiro** [comment]
Sorry guys for letting you wait for so long for my answer.

@jaysg I just tried the following:
1. Created the new Laravel app using the latest Laravel version
2. Installed iSeed
3. Created the `product_types` table with 3 test entries as per your SQL dump
4. Ran `php artisan iseed product_types`

Everything worked fine: Seed file was generated, and I was able to re-seed.

Can you share some more info about your dev environment? I'm running OSX with Laravel Valet + MariaDB.

@nermand The share() was replaced by the singleton() in https://github.com/orangehill/iseed/pull/85/files
Are you sure you're using the latest iSeed version?

**Comment by juslintek** [comment]
@tihomiro I'm using MySQL.
laravel new test_app
With homestead and its not working for me.

**Comment by nermand** [comment]
@tihomiro No, I am not, apparently. I failed to notice that I should update composer.json to use **dev-master** with an upgrade to 5.4.
Everything works perfectly now. Thanks!
