### ISSUE TITLE
Sorting with max records

### ISSUE THREAD

**Issue by Ardakilic** [orangehill/iseed#94]
Hey there,

If you add `--max=X` parameter, is there a way to add data in descending order, so the last X records are added. 

Something like:

```bash
php artisan iseed contacts --max=10 --sort=desc
```

Thanks in advance!

**Comment by tihomiro** [comment]
Hey @Ardakilic that would indeed be a nice feature, however, we're currently not planning on expanding the DB content splitting functionality (as in PHP Array kind of way).

**Comment by Ardakilic** [comment]
Hey @tihomiro , thanks for the reply. Keep up the good work! 👍
