### ISSUE TITLE
How to choose the version for laravel 5.1

### ISSUE THREAD

**Issue by BruceGujinhe** [orangehill/iseed#99]
the question as the title.

**Comment by archfrog** [comment]
The index page of the project states:

```
Laravel 5 versions less than 5.3.8

For Laravel 5 versions that are less than 5.3.8 edit your project's composer.json file to require 2.2 version:

"require": {
	"orangehill/iseed": "2.2"
}
```

I suppose that includes v5.1?

**Comment by tihomiro** [comment]
That's correct. 2.2 should work with L5.3. 

In the unlikely case that you have issues, you can always switch to 2.1.

 All the changes are documented in https://github.com/orangehill/iseed/releases
